site_name: EtherBench Documentation
site_url: https://lheywang.github.io/EtherBench/
extra_css:
  - scripts/style.css

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: premium
      primary: blue grey
      accent: indigo

  favicon: logos/debugger.png
  logo: logos/debugger.png
  icon:
    logo: logos/debugger.png

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - md_in_html
  - admonition
  - tables

plugins:
  - search
  - with-pdf:
      author: Leonard HEYWANG
      cover_title: "EtherBench Platform"
      cover_subtitle: "Technical Reference Manual"
      copyright: CERN-OHL-S v2 & GPLv3
      output_path: assets/etherbench_reference_manual.pdf
      cover: true
      back_cover: false
      toc_level: 3

nav:
  - Home: index.md
  - Installing:
      - installing/install.md
      - installing/configuring.md
  - Hardware:
      - hardware/hardware.md
      - hardware/mechanical.md
      - hardware/extensions.md
  - Programming:
      - programming/programming.md
      - programming/sequences.md
      - Markers:
          - programming/markers.md
          - programming/markers/markers_calibration.md
          - programming/markers/markers_name.md
          - programming/markers/markers_pages.md
          - programming/markers/markers_peripherals.md
          - programming/markers/markers_serial_number.md
      - Commands:
          - programming/generated/scpi_reference.md
  - Examples:
      - examples/examples.md
  - Architecure:
      - architecture/architecture.md
