site_name: EtherBench Documentation
site_url: https://lheywang.github.io/EtherBench/
repo_url: https://github.com/lheywang/EtherBench
repo_name: lheywang/EtherBench

hooks:
  - hooks.py

theme:
  name: material
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.prune
    - toc.follow
  palette:
    - scheme: premium
      primary: blue grey
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

  favicon: assets/icons/favicon.ico
  logo: assets/images/debugger.png

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: true
  - toc:
      permalink: true
  - mdx_truly_sane_lists:
      truly_sane: true
      nested_indent: 2
  - md_in_html
  - admonition
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/lheywang/EtherBench



plugins:
  - awesome-pages
  - search
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
          concurrency: 16
          stylesheets:
            - templates/pdf.scss
          aggregator:
            enabled: true
            output: assets/etherbench_reference_manual.pdf
            covers: limits
          covers:
            front: templates/front.html.j2
      buttons:
        - title: View as PDF
          icon: material-file-move-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes:
            target: _blank
            href: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.href
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes

nav:
  - Home: index.md
  - Table of Contents: toc.md
  - Installing:
      - Assembling:
          - installing/assembling/assembling.md
      - Software:
          - installing/software/install.md
          - installing/software/configuring.md

  - Hardware:
      - hardware/hardware.md
      - Mechanical:
          - hardware/mechanical/motherboard.md
          - hardware/mechanical/ui_board.md
          - hardware/mechanical/daugther_board.md
      - Electrical:
          - hardware/electrical/power.md
          - hardware/electrical/clocking.md
          - hardware/electrical/extensions.md
          - hardware/electrical/pinout.md
          - hardware/electrical/trigger.md
      - Thermal:
          - hardware/thermal/thermal.md

  - Programming:
      - programming/programming.md
      - Sequences:
          - programming/sequences/sequences.md
          - programming/sequences/internal.md
          - programming/sequences/external.md
      - Markers:
          - programming/markers.md
          - programming/markers/markers_battery.md
          - programming/markers/markers_calibration.md
          - programming/markers/markers_name.md
          - programming/markers/markers_pages.md
          - programming/markers/markers_peripherals.md
          - programming/markers/markers_serial_number.md
      - Commands:
          - programming/generated/scpi_reference.md

  - Examples:
      - examples/examples.md

  - Architecture:
      - architecture/architecture.md
      - Threads:
          - architecture/threads/org.md
          - Services:
            - architecture/threads/services/shell.md
          - Board_IO:
            - architecture/threads/board/board_manager.md
            
      - IO:
          - architecture/networking/network.md
          - Services:
              - architecture/networking/io/programmer.md
              - architecture/networking/io/scpi.md
              - architecture/networking/io/streaming.md
              - architecture/networking/io/telnet.md
      - Programmer:
          - architecture/jtag/jtag.md

extra_javascript:
  - assets/scripts/katex.js
  - assets/scripts/mathjax.js
  - assets/scripts/mkdocs-exporter.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
